site_name: Qxel Documentation
site_description: Documentation for Qxel - For Business, Users, and Partners
site_url: https://qxel.github.io/docs/

repo_name: qxel/docs
repo_url: https://github.com/qxel/docs

nav:
  - Home: index.md
  - Business:
    - Overview: business/index.md
    - Introduction: business/introduction.md
    - Get Started: business/get-started.md
    - Registration: business/registration.md
    - Data Entry: business/data_entry.md
    - Seo integration: business/seo_integration.md
    - Add Products: business/add_products.md
  - Users:
    - Overview: users/index.md
    - Introduction: users/introduction.md
    - Get Started: users/get-started.md
  - Partners:
    - Overview: partners/index.md
    - Introduction: partners/introduction.md
    - Get Started: partners/get-started.md

theme:
  name: material
  logo: https://cdn.jsdelivr.net/gh/mr-izu/Images@main/qxel.svg
  favicon: https://cdn.jsdelivr.net/gh/mr-izu/Images@main/qxel.svg
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-handle
      
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra

copyright: |
  &copy; 2024 Qxel, Inc. All rights Reserved.
  
extra:
  generator: false
